name: Run JPF

on:
  push:

jobs:
  run-jpf:
    name: '${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04, macos-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        ref: 651a4be8bd9e9fd45b16e23278b0196edd033ed0
  
    - name: Set up JDK 17 for project
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: maven

    - name: Build project with JDK 17 (if you do remove the above section, move this one under the "Set up JDK 11 for JPF" step!)
      run: cd vhr && mvn clean install -DskipTests -Dmaven.test.skip=true -Dmaven.compiler.test.compile.dependencies=true -Dmaven.compiler.test.classpath=true -Dmaven.test.failure.ignore=true -Dmaven.test.error.ignore=true -Dmaven.test.skip=true -Dmaven.test.skip.exec=true -Dmaven.test.skip.exec=true -Dmaven.test.skip.exec=true

    - name: Set up JDK 11 for JPF
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Clone and build jpf-core
      run: |
        git clone https://github.com/javapathfinder/jpf-core.git /tmp/jpf-core
        cd /tmp/jpf-core
        ./gradlew buildJars

    - name: Run JPF on JAR files
      shell: bash
      run: |
        #!/bin/bash
        set +e 
        
        directory=$(pwd)
        runjpf_jar="/tmp/jpf-core/build/RunJPF.jar"
        jar_files=$(find "$directory" -type f -name "*.jar")
        for jar_file in $jar_files; 
        do
            jar_dir=$(dirname "$jar_file")
            main_class=$(unzip -p "$jar_file" META-INF/MANIFEST.MF 2>/dev/null | grep -i 'Main-Class' | awk -F': ' '{print $2}' | tr -d '\r')
            if [ -z "$main_class" ]; then
                continue
            fi
            command="java -jar $runjpf_jar +classpath=$jar_file $main_class"
            $command
        done
